### ISSUE TITLE
default merge to dev branch?

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBEScore#105]
the default target location when one merges a branch appears to be the main. It is nice that contributors commit to dev, not directly to main. Is it possible to set the default target location of branch merges to dev instead of main?
@davidcurrie2001 @rix133 @nicholascarey

**Comment by nmprista** [comment]
How to
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

**Comment by nicholascarey** [comment]
Only Colin can access the setting pages to change this. However, I'm not sure it's necessary (and not sure if it might have unintended consequences). No-one can merge to Main directly - it has to be via a Pull Request from a different branch and approved by another maintainer.   

Also I think it's good practice that people need to think about which branches they are merging to and from anyway, rather than assuming defaults!

**Comment by davidcurrie2001** [comment]
Since we said we're not changing this lets close this issue.
