### ISSUE TITLE
doMultiStageEstimation  function

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBEScore#15]
Working on a function to do multi-stage sampling directly on **RDBESRawObject**. Most preliminary work is done in a vignette [Estimating Population parameters from RDBESRawObjects](https://github.com/ices-tools-dev/icesRDBES/blob/dev/vignettes/estimating-rdbesrawobjects.Rmd)

**Comment by rix133** [comment]
Renamed the main function and moved it to file [doMultiStageEstimation.R](https://github.com/ices-tools-dev/icesRDBES/blob/dev/R/doMultiStageEstimation.R), added tests. **Variance calculation is incomplete**. Some other TODO's also in the file.

**Comment by rix133** [comment]
the function does same thing as #18

**Comment by nmprista** [comment]
wgrdbes - consider the comments on #24

**Comment by rix133** [comment]
**[doEstimationForAllStrata](https://github.com/ices-tools-dev/RDBEScore/blob/dev/R/doEstimationForAllStrata.R)** has been agreed to be the function to be the  estimation function instead of https://github.com/ices-tools-dev/RDBEScore/issues/15  and https://github.com/ices-tools-dev/RDBEScore/issues/24

**Comment by rix133** [comment]
#71  tried to add tests from data from `survey` package 1 the total is ok but the total SE and mean seem of. I tried to check if the input data is ok (and it seems to be OK) so my best guess is that the function does not produce the expected result.

**Comment by nmprista** [comment]
I noticed some missing values in variable  'enroll' - the survey example seems to ignore them. the fpc2 variable entered into svytotal and svymean may perhap already account for that. Could different handling of NAs be part of the differences observed?

**Comment by rix133** [comment]
We can check but I don’t think so, anyhow it can’t make mean 6 times larger

**Comment by mrska** [comment]
The reason for different results between doEstimationForAllStrata and survey package is that
doEstimationForAllStrata - calculates the mean per vessel
whereas
survey - calculates the mean per vessel-trip

So now the question is - what do we want doEstimationForAllStrata  to calculate. And whether it should be hardcoded or given as a function parameter?

**Comment by rix133** [comment]
If we take the example now which is **SAsampWtMes** it would be only natural to assume that the mean is somewhere around the acutual mean of the sample weights. Right now it is about 6 time higher so it is not right either for trips or for vessel-trips

**Comment by rix133** [comment]
I still don't  get this.  If we are estimating the total **SAsampWtMes** we get total sampled weight per vessel per year. Now if we estimate the mean of it you are saying we are estimating the mean per vessel per year (i.e we are estimating how much in total one ship on average contributed to the sampled total)

**Comment by mrska** [comment]
First I would say that 0in this case I don't see much point of estimating SAsampWtMes. What is the sense of estimating total sampled weight per vessel if all what was sampled is in our dataset. So I think that what we should estimate and what makes sense is SAtotalWtMes. Is this dataset both values are the same, so the naming doesn't impact the results.

So assuming that we are working on SAtotalWtMes - we are using this variable to estimate total catch for the whole fleet (of 757 vessels in this case). And when calculating the mean - I think it makes sense to know the mean catch per vessel per year. And it also might be worthy to know mean catch per trip per year (what survey package is doing), depending on the analysis purpose.



> #71 tried to add tests from data from `survey` package. The **est.total** is ok but the **se.total** is slightly off. Also the **est.mean** and **se.mean** are about 6 and 12 times higher than expected. I tried to check if the input data is ok (and it seems to be OK) so my best guess is that the function does not produce the expected result.
> 
> Also I did a sanity check calculating the brute force mean ` mean(myEstData$SAsampWtMes, na.rm=T)` = 496 while `doEstimationForAllStrata(myEstData, 'SAsampWtMes')$est.mean` = 3486

When we calculate just mean SAtotalWtMes per vessel from the sampled data:
`myEstData %>% group_by(su1unitName) %>% summarise(a = sum(SAsampWtMes, na.rm = TRUE))) %>% ungroup() %>% summarise(mean(a)`
the result is 1489, which is still != 3486, but this is because big divergence between the vessels

**Comment by rix133** [comment]
I thonk it can be like this for now
