### ISSUE TITLE
Unexpected behavior of filterRDBESDataObject? 

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBEScore#183]
I get the expected result when I run the example
```
data("Pckg_survey_apistrat_H1_WGRDBES_EST_TEST_1")
filterRDBESDataObject(Pckg_survey_apistrat_H1_WGRDBES_EST_TEST_1, fieldsToFilter="SSid",valuesToFilter=227694, killOrphans = TRUE)
```
But not when I run
```
filterRDBESDataObject(Pckg_survey_apistrat_H1_WGRDBES_EST_TEST_1, fieldsToFilter="FOid",valuesToFilter=70849, killOrphans = TRUE)
```
Seems to be a problem with filtering by FOid but not SSid?

**Comment by rix133** [comment]
The best would be if you added a test to show what is the expected result (the test can fail if you don't know how to fix)   Having the call already is a good starting point. And it think it is a bug so I think this can be labeled as a bug

**Comment by rix133** [comment]
The issue was that the "`FOid`" field exists in several tables so it is also on the `FT` table (although NA) as not used. So filtering it also filtered the `FT` and hence the strange behaviour.

The solution is to remove all the other id fields from the `FT` table except `FTid` when filtering. So the current implementation I'll push enables to filter on an id field only if it is the id of that table. I think this makes things less confusing although it is not very flexible as you might want to filter on an id field but (like `FOid`  on `FT`  ) but can't.  To enable this feature requires explicitly stating on the `filterRDBESDataObject` call the table where the id is expected. But is this actually required feature?

**Comment by rix133** [comment]
pushed the fix in dev
