### ISSUE TITLE
createRDBESDataObject

### ISSUE THREAD

**Issue by Kasia-MIR** [ices-tools-dev/RDBEScore#210]
read.csv isn't sufficient function to read data. 

Suggestion: use data.table::fread(file_path, stringsAsFactors=FALSE, verbose=FALSE, sep=",", na.strings="NULL",quote = "")

**Comment by davidcurrie2001** [comment]
I've added some tests to check that the number of rows created when you import CSV data is correct.  I've also added a copy of CL with bad data in the vessel identifiers field to the test data.

I think the problem is that you can currently upload vessel ids separated by commas in CLencryptedVesselIds if you quote the data (i.e. "abc,def,ghi") – but when you download that data you only get partial data values from that field (e.g. "abc).  

I’ve raised an issue on the RDBES core group GitHub to request a check for commas during upload: https://github.com/ices-tools-dev/RDBES/issues/212
