### ISSUE TITLE
update input files in "Raw Data Import" vignette

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBEScore#40]
@davidcurrie2001 I tested vignette "Raw Data Import" with testthat data and my own data and seems to be working. Only thing is that the new zip files from v.1.19.13 now include the CS together with SL and VD in a single zip. Maybe update we should update the example? and to keep the demo you already have by replacing current HVD_*.zip and HSL_*.zip for a HCL_*.zip and HCE_*.zip?

_Originally posted by @nmprista in https://github.com/ices-tools-dev/icesRDBES/issues/28#issuecomment-1272591212_

**Comment by nicholascarey** [comment]
I have been revising this vignette. I think the data this vignette uses needs to be in the `/data` folder rather than the `tests` folder, otherwise a user installing the package will not be able to run the code. If we could discuss what sample or test data to include in the package as a whole. There should be enough to demonstrate all the functions, both for users to run as examples and for building vignettes, but obviously not too much.
