### ISSUE TITLE
vignette calc-zeroes-and-probs.Rmd needs fixing

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBEScore#94]
checks("RDBEScore") currently returning
![image](https://github.com/ices-tools-dev/RDBEScore/assets/31890653/803a035b-e1f1-45bf-84d0-40dfab33847a)

**Comment by KirstenBirchHaakansson** [comment]
I think this vignette should be split into two, since it handles very different topic, so one for manipulation of SA based on SL and one for probabilities, so the latter is moved to #123

**Comment by KirstenBirchHaakansson** [comment]
Add documentation of how we interpret the combination of fields relevant for this e.g., catchReg, sampled

**Comment by nicholascarey** [comment]
Note on `dev` i commented out all code in the vignettes that are not working since if they don't run without error it means i can't build the website.  

So just a note for the future when you are working on them - make sure they knit without error - even if that menas just commenting out code. 

Thanks!
